### ISSUE TITLE
Bug: Android: There was a problem parsing the package

### ISSUE THREAD

**Issue by seyyah** [b-erdem/sms-im#1]
Your generated [apk](https://github.com/b-erdem/sms-im/blob/master/resources/apk/app-debug.apk) gives this error. How to solve it?

In Turkish: "Paketin ayrıştırılmasında bir sorun oluştu."

**Comment by b-erdem** [comment]
Can you provide your phone’s OS version?

**Comment by seyyah** [comment]
Android version: 7.0

![image](https://user-images.githubusercontent.com/263237/66046117-bf764900-e52d-11e9-80fd-6bbae6fb5b2b.png)

**Comment by b-erdem** [comment]
I made new update for supporting Android 7(API level 23). You should be able to use the app without any error now.

**Comment by seyyah** [comment]
This commit (b51b490eec885e80f3d0a12eb19a60397abed2c0) fixed my problem. Thanks a lot
